Update build-kernel.yml

diff --git a/.github/workflows/build-kernel.yml b/.github/workflows/build-kernel.yml
--- a/.github/workflows/build-kernel.yml
+++ b/.github/workflows/build-kernel.yml
@@ -97,7 +97,6 @@ jobs:
       with:
         swap-size-gb: 10
 
-
     - name: Setup kernel build environment
       run: |
         echo "BUILD_TIME=$(TZ=Asia/Dhaka date "+%Y%m%d%H%M")" >> $GITHUB_ENV
@@ -123,94 +122,40 @@ jobs:
         rm -rf ~/python2-jammy
 
     - name: Download Clang
-      if: env.USE_CLANG == 'true' && env.USE_GCC != 'true'
+      if: env.USE_CLANG == 'true'
       run: |
         cd $GITHUB_WORKSPACE/kernel_workspace
-        if [[ ${{ env.CLANG_SOURCE }} == *'.tar.gz' ]]; then
-            wget -nv -O clang.tar.gz ${{ env.CLANG_SOURCE }}
-            mkdir clang
-            tar -C clang/ -zxvf clang.tar.gz
-            rm clang.tar.gz
-        elif [[ ${{ env.CLANG_SOURCE }} == *'.tar.xz' ]]; then
-            wget -nv -O clang.tar.xz ${{ env.CLANG_SOURCE }}
-            mkdir clang
-            tar -C clang/ -Jxvf clang.tar.xz
-            rm clang.tar.xz
-        elif [[ ${{ env.CLANG_SOURCE }} == *'.tar.zst' ]]; then
-            wget -nv -O clang.tar.zst ${{ env.CLANG_SOURCE }}
-            mkdir clang
-            tar -C clang/ -I zstd -xf clang.tar.zst
-            rm clang.tar.zst
-        elif [[ ${{ env.CLANG_SOURCE }} == *'.git' ]]; then
-            git clone ${{ env.CLANG_SOURCE }} -b ${{ env.CLANG_BRANCH }} clang --depth=1
-        else
-            wget -nv -O clang.zip ${{ env.CLANG_SOURCE }}
-            mkdir clang
-            unzip clang.zip -d clang/
-        fi
-        if [[ "$(find ./clang -mindepth 1 -maxdepth 1 -type d | wc -l)" == "1" ]]; then
-            mv -f "$(find ./clang -mindepth 1 -maxdepth 1 -type d)"/* ./clang
-        fi
+        wget -nv -O clang.tar.xz https://github.com/llvm/llvm-project/releases/download/llvmorg-17.0.6/clang+llvm-17.0.6-aarch64-linux-gnu.tar.xz
+        mkdir clang
+        tar -C clang/ -Jxvf clang.tar.xz --strip-components=1
+        rm clang.tar.xz
+        echo "Listing Clang binaries:"
+        ls -l clang/bin
+        for bin in clang ld.lld llvm-as llvm-ar llvm-nm llvm-objcopy llvm-objdump llvm-readelf llvm-strip; do
+          test -f clang/bin/$bin && echo "Found: $bin" || echo "Missing: $bin"
+        done
 
     - name: Download GCC
-      if: env.USE_GCC == 'true' && env.USE_CLANG != 'true'
+      if: env.USE_GCC == 'true'
       run: |
         cd $GITHUB_WORKSPACE/kernel_workspace
         if [ ${{ env.USE_GCC_64 }} = true ]; then
-            if [[ ${{ env.GCC_64_SOURCE }} == *'.tar.gz' ]]; then
-                wget -nv -O gcc-64.tar.gz ${{ env.GCC_64_SOURCE }}
-                mkdir gcc-64
-                tar -C gcc-64/ -zxvf gcc-64.tar.gz
-                rm gcc-64.tar.gz
-            elif [[ ${{ env.GCC_64_SOURCE }} == *'.tar.xz' ]]; then
-                wget -nv -O gcc-64.xz ${{ env.GCC_64_SOURCE }}
-                mkdir gcc-64
-                tar -C gcc-64/ -Jxvf gcc-64.xz
-                rm gcc-64.tar.xz
-            elif [[ ${{ env.GCC_64_SOURCE }} == *'.tar.zst' ]]; then
-                wget -nv -O gcc-64.tar.zst ${{ env.GCC_64_SOURCE }}
-                mkdir gcc-64
-                tar -C gcc-64/ -I zstd -xf gcc-64.tar.zst
-                rm gcc-64.tar.zst
-            elif [[ ${{ env.GCC_64_SOURCE }} == *'.git' ]]; then
-                git clone ${{ env.GCC_64_SOURCE }} -b ${{ env.GCC_64_BRANCH }} gcc-64 --depth=1
-            else
-                wget -nv -O gcc-64.zip ${{ env.GCC_64_SOURCE }}
-                mkdir gcc-64
-                unzip gcc-64.zip -d gcc-64/
-                rm gcc-64.zip
-            fi
-            if [[ "$(find ./gcc-64 -mindepth 1 -maxdepth 1 -type d | wc -l)" == "1" ]]; then
-                mv -f "$(find ./gcc-64 -mindepth 1 -maxdepth 1 -type d)"/* ./gcc-64
-            fi
+            wget -nv -O gcc-64.tar.xz ${{ env.GCC_64_SOURCE }}
+            mkdir gcc-64
+            tar -C gcc-64/ -Jxvf gcc-64.tar.xz --strip-components=1
+            rm gcc-64.tar.xz
+            echo "Listing GCC 64-bit binaries:"
+            ls -l gcc-64/bin
+            test -f gcc-64/bin/aarch64-linux-gnu-gcc && echo "Found: aarch64-linux-gnu-gcc" || echo "Missing: aarch64-linux-gnu-gcc"
         fi
         if [ ${{ env.USE_GCC_32 }} = true ]; then
-            if [[ ${{ env.GCC_32_SOURCE }} == *'.tar.gz' ]]; then
-                wget -nv -O gcc-32.tar.gz ${{ env.GCC_32_SOURCE }}
-                mkdir gcc-32
-                tar -C gcc-32/ -zxvf gcc-32.tar.gz
-                rm gcc-32.tar.gz
-            elif [[ ${{ env.GCC_32_SOURCE }} == *'.tar.xz' ]]; then
-                wget -nv -O gcc-32.xz ${{ env.GCC_32_SOURCE }}
-                mkdir gcc-32
-                tar -C gcc-32/ -Jxvf gcc-32.xz
-                rm gcc-32.tar.xz
-            elif [[ ${{ env.GCC_32_SOURCE }} == *'.tar.zst' ]]; then
-                wget -nv -O gcc-32.tar.zst ${{ env.GCC_32_SOURCE }}
-                mkdir gcc-32
-                tar -C gcc-32/ -I zstd -xf gcc-32.tar.zst
-                rm gcc-32.tar.zst
-            elif [[ ${{ env.GCC_32_SOURCE }} == *'.git' ]]; then
-                git clone ${{ env.GCC_32_SOURCE }} -b ${{ env.GCC_32_BRANCH }} gcc-32 --depth=1
-            else
-                wget -nv -O gcc-32.zip ${{ env.GCC_32_SOURCE }}
-                mkdir gcc-32
-                unzip gcc-32.zip -d gcc-32/
-                rm gcc-32.zip
-            fi
-            if [[ "$(find ./gcc-32 -mindepth 1 -maxdepth 1 -type d | wc -l)" == "1" ]]; then
-                mv -f "$(find ./gcc-32 -mindepth 1 -maxdepth 1 -type d)"/* ./gcc-32
-            fi
+            wget -nv -O gcc-32.tar.xz ${{ env.GCC_32_SOURCE }}
+            mkdir gcc-32
+            tar -C gcc-32/ -Jxvf gcc-32.tar.xz --strip-components=1
+            rm gcc-32.tar.xz
+            echo "Listing GCC 32-bit binaries:"
+            ls -l gcc-32/bin
+            test -f gcc-32/bin/arm-linux-gnueabi-gcc && echo "Found: arm-linux-gnueabi-gcc" || echo "Missing: arm-linux-gnueabi-gcc"
         fi
 
     - name: Download mkbootimg tools
@@ -224,19 +169,29 @@ jobs:
         cd $GITHUB_WORKSPACE/kernel_workspace
         git clone --recursive ${{ env.KERNEL_SOURCE }} -b ${{ env.KERNEL_SOURCE_BRANCH }} android-kernel --depth=1
 
+    - name: Apply Kconfig patch
+      run: |
+        cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
+        if [ -f $GITHUB_WORKSPACE/patches/fix_kconfig.patch ]; then
+            git apply $GITHUB_WORKSPACE/patches/fix_kconfig.patch
+        else
+            echo "Kconfig patch not found, skipping"
+        fi
 
     - name: Disable strong stack protector
       run: |
         cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
-        echo "this list ls :"
-        ls
-        echo " this is list scripts:"
-        ls scripts
-        echo "this file config:"
+        echo "Listing scripts directory:"
+        ls -l scripts
+        echo "Checking scripts/config existence:"
         ls -l scripts/config
         make ARCH=arm64 ${DEVICE}_defconfig
-        scripts/config --disable CONFIG_CC_STACKPROTECTOR_STRONG
+        ./scripts/config --disable CONFIG_CC_STACKPROTECTOR_STRONG
+        echo "Verifying CONFIG_CC_STACKPROTECTOR_STRONG is disabled:"
+        grep CONFIG_CC_STACKPROTECTOR_STRONG out/.config || echo "CONFIG_CC_STACKPROTECTOR_STRONG not found"
         make ARCH=arm64 olddefconfig
+        echo "Final .config contents for stack protector:"
+        grep CONFIG_CC_STACKPROTECTOR out/.config || echo "No stack protector configs found"
 
     - name: Download source boot image
       if: env.BUILD_BOOT_IMG == 'true'
@@ -360,69 +315,59 @@ jobs:
       run: |
         cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
         if [ ${{ env.USE_GCC }} = true ]; then
-            if [ ${{ env.USE_GCC_64 }} = true ]; then
-                export PATH=$GITHUB_WORKSPACE/kernel_workspace/gcc-64/bin:$PATH
-            fi
-            if [ ${{ env.USE_GCC_32 }} = true ]; then
-                export PATH=$GITHUB_WORKSPACE/kernel_workspace/gcc-32/bin:$PATH
-            fi
+            export PATH=$GITHUB_WORKSPACE/kernel_workspace/gcc-64/bin:$GITHUB_WORKSPACE/kernel_workspace/gcc-32/bin:$PATH
+            echo "Using GCC toolchain"
+            export CC=aarch64-linux-gnu-gcc
+            export CROSS_COMPILE=aarch64-linux-gnu-
+            export CROSS_COMPILE_ARM32=arm-linux-gnueabi-
+            export CROSS_COMPILE_COMPAT=arm-linux-gnueabi-
         elif [ ${{ env.USE_CLANG }} = true ]; then
             export PATH=$GITHUB_WORKSPACE/kernel_workspace/clang/bin:$PATH
+            echo "Using Clang toolchain"
+            export CC=clang
+            export CROSS_COMPILE=aarch64-linux-gnu-
+            export CROSS_COMPILE_ARM32=arm-linux-gnueabi-
+            export CROSS_COMPILE_COMPAT=arm-linux-gnueabi-
         else
             echo "Toolchain not selected"
             exit 1
         fi
-        # Add this block right here, after setting PATH
         echo "Checking for required toolchain binaries:"
-        for bin in clang ld.lld llvm-as llvm-ar llvm-nm llvm-objcopy llvm-objdump llvm-readelf llvm-strip aarch64-linux-gnu-gcc arm-linux-gnueabi-gcc; do
+        for bin in $CC ld.lld llvm-as llvm-ar llvm-nm llvm-objcopy llvm-objdump llvm-readelf llvm-strip aarch64-linux-gnu-gcc arm-linux-gnueabi-gcc; do
           which $bin || echo "Missing: $bin"
         done
-
         export KBUILD_BUILD_HOST=Github-Action
         export KBUILD_BUILD_USER=$(echo ${{ github.actor }} | tr A-Z a-z)
-        if [ -n ${{ env.KSU_EXPECTED_SIZE }} ] && [ -n ${{ env.KSU_EXPECTED_HASH }} ]; then
+        if [ -n "${{ env.KSU_EXPECTED_SIZE }}" ] && [ -n "${{ env.KSU_EXPECTED_HASH }}" ]; then
           export KSU_EXPECTED_SIZE=${{ env.KSU_EXPECTED_SIZE }}
           export KSU_EXPECTED_HASH=${{ env.KSU_EXPECTED_HASH }}
         fi
         echo "test EXTRA_CMDS="
         echo $EXTRA_CMDS
-        make V=1 -j$(nproc --all) CC=clang O=out ARCH=${{ env.KERNEL_ARCH }} ${{ env.EXTRA_CMDS }} ${DEVICE}_defconfig
+        make V=1 -j$(nproc --all) CC=$CC O=out ARCH=${{ env.KERNEL_ARCH }} CROSS_COMPILE=$CROSS_COMPILE CROSS_COMPILE_ARM32=$CROSS_COMPILE_ARM32 CROSS_COMPILE_COMPAT=$CROSS_COMPILE_COMPAT CONFIG_NO_ERROR_ON_MISMATCH=y TARGET_BUILD_VARIANT=user ${DEVICE}_defconfig
         if [ ${{ env.ENABLE_CCACHE }} = true ]; then
-            if [ ${{ env.USE_GCC }} = true ]; then
-             
-                make  -j$(nproc --all) CC="ccache gcc" O=out ARCH=${{ env.KERNEL_ARCH }} ${{ env.EXTRA_CMDS }}
-            else
-                echo "test EXTRA_CMDS="
-                echo $EXTRA_CMDS
-                make  -j$(nproc --all) CC="ccache clang" O=out ARCH=${{ env.KERNEL_ARCH }} ${{ env.EXTRA_CMDS }}
-            fi
+            make -j$(nproc --all) CC="ccache $CC" O=out ARCH=${{ env.KERNEL_ARCH }} CROSS_COMPILE=$CROSS_COMPILE CROSS_COMPILE_ARM32=$CROSS_COMPILE_ARM32 CROSS_COMPILE_COMPAT=$CROSS_COMPILE_COMPAT CONFIG_NO_ERROR_ON_MISMATCH=y TARGET_BUILD_VARIANT=user
         else
-            if [ ${{ env.USE_GCC }} = true ]; then
-                make  -j$(nproc --all) CC=gcc O=out ARCH=${{ env.KERNEL_ARCH }} ${{ env.EXTRA_CMDS }}
-            else
-                echo "test EXTRA_CMDS="
-                echo $EXTRA_CMDS
-                make  -j$(nproc --all) CC=clang O=out ARCH=${{ env.KERNEL_ARCH }} ${{ env.EXTRA_CMDS }}
-            fi
+            make -j$(nproc --all) CC=$CC O=out ARCH=${{ env.KERNEL_ARCH }} CROSS_COMPILE=$CROSS_COMPILE CROSS_COMPILE_ARM32=$CROSS_COMPILE_ARM32 CROSS_COMPILE_COMPAT=$CROSS_COMPILE_COMPAT CONFIG_NO_ERROR_ON_MISMATCH=y TARGET_BUILD_VARIANT=user
         fi
 
     - name: Check a kernel output files
       run: |
-       cd $GITHUB_WORKSPACE/kernel_workspace
-       if [ -f android-kernel/out/arch/${{ env.KERNEL_ARCH }}/boot/${{ env.KERNEL_IMAGE_NAME }} ]; then
-           echo "CHECK_FILE_IS_OK=true" >> $GITHUB_ENV
-       else
-           echo "Kernel output file is empty"
-           exit 1
-       fi
-       if [ ${{ env.NEED_DTBO }} = true ]; then
-           if [ -f android-kernel/out/arch/${{ env.KERNEL_ARCH }}/boot/dtbo.img ]; then
-               echo "CHECK_DTBO_IS_OK=true" >> $GITHUB_ENV
-           else
-               echo "DTBO image is empty"
-               exit 1
-           fi
-       fi
+        cd $GITHUB_WORKSPACE/kernel_workspace
+        if [ -f android-kernel/out/arch/${{ env.KERNEL_ARCH }}/boot/${{ env.KERNEL_IMAGE_NAME }} ]; then
+            echo "CHECK_FILE_IS_OK=true" >> $GITHUB_ENV
+        else
+            echo "Kernel output file is empty"
+            exit 1
+        fi
+        if [ ${{ env.NEED_DTBO }} = true ]; then
+            if [ -f android-kernel/out/arch/${{ env.KERNEL_ARCH }}/boot/dtbo.img ]; then
+                echo "CHECK_DTBO_IS_OK=true" >> $GITHUB_ENV
+            else
+                echo "DTBO image is empty"
+                exit 1
+            fi
+        fi
 
     - name: Patch SukiSU Ultra KPM
       if: env.CHECK_FILE_IS_OK == 'true' && env.KPM_SUPPORT == 'true'
@@ -457,7 +402,7 @@ jobs:
         elif [[ ${{ env.ANYKERNEL3_SOURCE }} == *'.tar.zst' ]]; then
             wget -nv -O AnyKernel3.tar.zst ${{ env.ANYKERNEL3_SOURCE }}
             mkdir AnyKernel3
-            tar -C AnyKernel3/ -I zstd -xf clang.tar.zst
+            tar -C AnyKernel3/ -I zstd -xf AnyKernel3.tar.zst
             rm AnyKernel3.tar.zst
         elif [[ ${{ env.ANYKERNEL3_SOURCE }} == *'.git' ]]; then
             git clone ${{ env.ANYKERNEL3_SOURCE }} -b ${{ env.ANYKERNEL3_BRANCH }} --depth=1 AnyKernel3
